<?php
include_once("header.php");
include_once("menu.php");
include_once("menu_celular.php");
include_once("notas_1.php");
include_once("en_vivo.php");
include_once("notas_2.php");
include_once("notas_3.php");
include_once("notas_4.php");
include_once("notas_5.php");
include_once("footer.php");